# Jekyll Resume Theme

# Site settings
title: David Mueller
email: ""
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://davidm.de"
name: David M&uuml;ller
location: San Jose, California
twitter_username: davidm_ller
github_username:  dvdmllr
linkedin_username: dvdmllr 
quora_address: David-M%C3%BCller-1

# Build settings
markdown: kramdown
